cas:
  # cas服务端的地址
  server-url-prefix: http://localhost:8443/cas
  # cas服务端的登录地址
  server-login-url: http://localhost:8443/cas/login
  # 当前服务器的地址(客户端)
  client-host-url: http://localhost:9003
  # Ticket校验器使用Cas30ProxyReceivingTicketValidationFilter
  validation-type: cas3
server:
  port: 9004
  servlet:
    context-path: /client3